### ISSUE TITLE
There was a problem compiling the kernel.

### ISSUE THREAD

**Issue by MelOnva** [Chatur27/Eureka-kernel-for-SM-A105-Q#5]
There was a problem compiling the kernel.

Error: file not found: /home/kim-doil/Work/Eureka-Kernel-Exynos7885-Q-R/firmware/tsp_zinitix/zt7548_a40.fw
...
There is no fw file, and when you access the directory, there is only the .fw.ihex file.

Is there a way to create or download an fw file?

Thanks.

[log.txt](https://github.com/Chatur27/Eureka-Kernel-Exynos7885-Q-R/files/7356918/log.txt)

**Comment by Chatur27** [comment]
Hi, this is an old kernel source. The latest kernel source can be found at: https://github.com/eurekadevelopment/Eureka-Kernel-Exynos7885-Q-R
